from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.database.db import get_db

from app.schemas.interpretation import (
    EvidenceSummary,
    InterpretationAlternative,
    InterpretationRequest,
    InterpretationResponse,
    SourceResponse,
)

from app.services.interpretation_engine import (
    InterpretationResult,
    aggregate_evidence,
    interpret_observation,
)


router = APIRouter(
    prefix="/interpret",
    tags=["interpretation"],
)


def _to_response_item(
    result: InterpretationResult,
) -> InterpretationAlternative:
    return InterpretationAlternative(
        rule_key=result.rule_key,
        label=result.interpretation_label,
        description=result.interpretation_description,

        system_match_score=result.confidence_score,

        scientific_evidence=result.evidence_level,
        evidence_basis=result.evidence_basis,

        context_matched=result.matched_context,

        matched_supporting_signals=(
            result.matched_supporting_signals
        ),

        missing_supporting_signals=(
            result.missing_supporting_signals
        ),

        limitations=result.limitations,

        sources=[
            SourceResponse(
                key=source.key,
                title=source.title,
                authors=source.authors,
                year=source.year,
                journal=source.journal,
                doi=source.doi,
                url=source.url,
            )
            for source in result.sources
        ],
    )


def _build_evidence_summary(
    results: list[InterpretationResult],
) -> EvidenceSummary:
    """
    Convert internal engine evidence objects
    into API response schema.
    """

    evidence_data = aggregate_evidence(results)

    return EvidenceSummary(
        evidence_basis=evidence_data["evidence_basis"],
        limitations=evidence_data["limitations"],
        sources=[
            SourceResponse(
                key=source.key,
                title=source.title,
                authors=source.authors,
                year=source.year,
                journal=source.journal,
                doi=source.doi,
                url=source.url,
            )
            for source in evidence_data["sources"]
        ],
    )


@router.post(
    "",
    response_model=InterpretationResponse,
)
def interpret(
    request: InterpretationRequest,
    db: Session = Depends(get_db),
) -> InterpretationResponse:

    try:
        results = interpret_observation(
            db=db,
            species_slug=request.species,
            signals=request.signals,
            context_slug=request.context,
        )

    except ValueError as exc:
        raise HTTPException(
            status_code=404,
            detail=str(exc),
        ) from exc


    if not results:
        return InterpretationResponse(
            status="insufficient_evidence",
            species=request.species,
            observed_signals=request.signals,
            context=request.context,

            primary_interpretation=None,
            alternatives=[],

            evidence_summary=None,

            disclaimer=(
                "The available research-backed rules do not "
                "support a sufficiently specific interpretation "
                "for the provided observation."
            ),
        )


    response_results = [
        _to_response_item(result)
        for result in results
    ]


    primary = response_results[0]

    alternatives = response_results[1:]


    evidence_summary = _build_evidence_summary(
        results
    )


    return InterpretationResponse(
        status="interpreted",

        species=request.species,

        observed_signals=request.signals,

        context=request.context,


        primary_interpretation=primary,

        alternatives=alternatives,


        evidence_summary=evidence_summary,


        disclaimer=(
            "The system match score is generated by the "
            "application's rule-matching algorithm. It is not "
            "a probability reported by the cited scientific "
            "studies and should not be interpreted as a literal "
            "translation of animal language."
        ),
    )
